#! /bin/sh
## Resetting BSPWM rule
bspc rule -r "*"
## Launching Polybar
~/.config/polybar/./launch.sh
## Keyboard shortcuts daemon
sxhkd &
## Notification Daemon
dunst -config ~/.config/dunst/dunstrc &
## Picom Compositor
#picom --experimental-backends &
## Polybar
#polybar example &
## Policy Kit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
## Tab To click [ Touchpad ] bash script
# powermanager
xfce4-power-manager &

~/.fehbg

# BSPWM configuration
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius 4
bspc config bottom_padding 0
bspc config top_padding 0
# BSP RULES
#bspc rule -a tint2 border=off manage=off layer=above

bspc rule -a Plank layer=above manage=on border=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color1    5"
#bspc config presel_feedback_color "$color    1"
bspc config focus_follows_pointer true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

#############################--PYWALL--###################################
# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

############################--PYWALL--###################################


#bspc rule -a Spotify state=floating rectangle=500x500+500+500 sticky=off
#bspc rule -a Alacritty state=floating rectangle 600x900+200+50 sticky=off
bspc rule -a Pavucontrol state=floating rectangle 600x500+50+50 sticky=off center=true
bspc rule -a Termite_float state=floating rectangle 700x450+50+50 sticky=off center=true
bspc rule -a Sxiv state=floating rectangle 600x500+50+50 sticky=off center=true

# Remove x cursor
xsetroot -cursor_name left_ptr & 


