#! /bin/sh
bspc rule -r "*"

~/.config/polybar/./launch.sh

sxhkd &
dunst -config ~/.config/dunst/dunstrc &
picom --experimental-backends &
polybar example &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/tab_to_click

# BSPWM configuration
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius 8
bspc config bottom_padding 0
bspc config top_padding 8
# BSP RULES
bspc rule -a Plank layer=above manage=on border=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1    5"
bspc config presel_feedback_color "$color    1"
bspc config focus_follows_pointer true

#bspc rule -a Spotify state=floating rectangle=500x500+500+500 sticky=off
#bspc rule -a Alacritty state=floating rectangle 600x900+200+50 sticky=off
#bspc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off 

# Remove x cursor
xsetroot -cursor_name left_ptr & 


